import time
from typing import List, Dict, Any
from dataclasses import dataclass, field
from src.agent.monitor import InvestigationSession

@dataclass
class AttentionQueueItem:
    priority: str
    situation: str
    location: str
    camera: str
    entity: str
    duration: float
    evidence: str
    reason: str
    freshness: float
    investigation_status: str
    investigation_session: InvestigationSession
    score: float = 0.0

class AttentionQueue:
    """
    Operator Attention Queue.
    Maintains a sorted queue of active investigations based on priority, freshness, and persistence.
    """
    
    PRIORITY_WEIGHTS = {
        "CRITICAL": 100000,
        "HIGH": 10000,
        "MEDIUM": 1000,
        "LOW": 100,
        "INFORMATIONAL": 0
    }
    
    def __init__(self):
        self._items: Dict[str, AttentionQueueItem] = {}
        
    def add_or_update(self, session: InvestigationSession):
        # Calculate a ranking score
        base_score = self.PRIORITY_WEIGHTS.get(session.priority, 0)
        
        # Freshness: newer updates get a slight bump (decay over time)
        # Assuming session.updated_at is a unix timestamp
        age = time.time() - session.updated_at
        freshness_score = max(0, 10 - age/60) # Decays over 10 minutes
        
        # Persistence: duration or number of observations
        persistence_score = len(session.observations) * 0.5
        
        total_score = base_score + freshness_score + persistence_score
        
        # Extract metadata from facts / candidate for UI
        # We rely on facts generated by the reasoner or session context
        camera_list = ",".join(session.evidence_consulted) if session.evidence_consulted else "Unknown"
        
        item = AttentionQueueItem(
            priority=session.priority,
            situation="Review Required" if session.recommended_operator_attention == "REVIEW" else "Observation",
            location="See Details",
            camera=camera_list,
            entity="See Details",
            duration=age,
            evidence="Yes" if session.evidence_consulted else "No",
            reason=session.facts[0] if session.facts else "Unknown",
            freshness=age,
            investigation_status=session.status,
            investigation_session=session,
            score=total_score
        )
        
        self._items[session.investigation_id] = item
        
    def get_sorted_queue(self) -> List[AttentionQueueItem]:
        """
        Returns items sorted by descending score (priority + freshness + persistence).
        """
        return sorted(self._items.values(), key=lambda x: x.score, reverse=True)
        
    def resolve(self, investigation_id: str):
        if investigation_id in self._items:
            del self._items[investigation_id]
